name: Sync Fork Source

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout fork-source branch
        uses: actions/checkout@v4
        with:
          ref: fork-source
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/THUDM/slime.git

      - name: Sync with upstream main
        run: |
          git fetch upstream main
          git reset --hard upstream/main

      - name: Push updated fork-source
        run: git push origin HEAD:fork-source
